export interface PhotoSpec {
  specCode: string;
  specCodeInEnglish: string;
  headHeightText: string;
  eyeToBottomText: string;
  bgColorText: string;
  dpi: number;
  unit: string;
  widthPx: number;
  widthUnit: number;
  heightPx: number;
  heightUnit: number;
}

export function copyPhotoSpec(old: PhotoSpec): PhotoSpec {
  return { ...old };
}

export const allSpecCodes = [
  "1.5x1.5-inch",
  "1.5x2-inch",
  "1x1-inch",
  "20x30-mm",
  "25x30-mm",
  "25x35-mm",
  "26x32-mm",
  "2x2-inch",
  "30x40-mm",
  "33x48-mm",
  "35x40-mm",
  "35x45-mm",
  "40x40-mm",
  "40x50-mm",
  "40x60-mm",
  "50x50-mm",
  "50x70-mm",
  "51x70-mm",
  "albania-passport",
  "argentina-passport",
  "argentina-visa",
  "australia-baby-passport",
  "australia-nsw-driving-license",
  "australia-passport",
  "australia-proof-of-age-card",
  "australia-queensland-driving-license",
  "australia-visa",
  "baby-passport",
  "bahrain-passport",
  "bahrain-visa",
  "bangladesh-passport",
  "bangladesh-visa",
  "belarus-passport",
  "belarus-visa",
  "belgium-passport",
  "brazil-cnh",
  "brazil-id",
  "brazil-passport",
  "brazil-passport-old-standard",
  "brazil-visa",
  "brazil-work",
  "bulgaria-passport",
  "bulgaria-visa",
  "cambodia-passport",
  "cambodia-visa",
  "canada-baby-passport",
  "canada-citizenship",
  "canada-firearms-license",
  "canada-passport",
  "canada-permanent-residence",
  "canada-permanent-resident-card",
  "canada-temporary-residence-permit",
  "canada-visa",
  "chile-visa",
  "china-passport",
  "china-taiwan",
  "china-visa",
  "colombia-passport",
  "colombia-visa",
  "costarica-passport",
  "costco-passport",
  "croatia-passport",
  "cuba-passport",
  "cuba-visa",
  "cvs-passport",
  "cyprus-passport",
  "cyprus-visa",
  "czechrepublic-passport",
  "czechrepublic-visa",
  "denmark-passport",
  "dubai-evisa",
  "dubai-visa",
  "dutch-passport",
  "egypt-passport",
  "esn-card-photo-for-turku-exchange-student",
  "estonia-passport",
  "estonia-visa",
  "european-athletics",
  "europeanunion-passport",
  "europeanunion-visa",
  "fedex-passport",
  "finland-digital-passport",
  "finland-driving-license",
  "finland-idcard",
  "finland-passport",
  "finland-passport2",
  "finland-visa",
  "football-player",
  "foto-25x30",
  "foto-2x2",
  "foto-35x45",
  "foto-3x4",
  "foto-4x5",
  "foto-5x7",
  "france-carte-vitale",
  "france-passport",
  "france-visa",
  "franch-driver ",
  "franch-id-card",
  "french-passport",
  "germany-disability-card",
  "germany-driving-license",
  "germany-health-insurance-card",
  "germany-id",
  "germany-passport",
  "germany-permanent-residence",
  "germany-rail-card",
  "germany-residence-permit",
  "germany-resume",
  "germany-visa",
  "ghana-passport",
  "ghana-visa",
  "ghana-visa1",
  "greece-passport",
  "greece-visa",
  "hayya-card",
  "hk-china-permit-multiple",
  "hk-china-permit-single",
  "hk-passport-digital",
  "hungary-passport",
  "hungary-visa",
  "illinois-foid",
  "india-evisa-350",
  "india-oci",
  "india-passport",
  "india-visa",
  "india-visa-2x2-inch",
  "indonesia-passport",
  "indonesia-visa",
  "iran-passport",
  "iran-visa",
  "ireland-digital-passport",
  "ireland-driverlicense",
  "ireland-passport",
  "ireland-visa",
  "isic-card",
  "israel-passport",
  "israel-visa",
  "italy-passport",
  "italy-visa",
  "jamaica-passport",
  "jamaica-visa",
  "japan-driverlicense",
  "japan-english",
  "japan-id",
  "japan-my-number",
  "japan-passport",
  "japan-resume",
  "japan-resume-small-head",
  "japan-toeic",
  "japan-visa",
  "kenya-passport",
  "kenya-visa",
  "kuwait-passport",
  "kuwait-visa",
  "lebanon-passport",
  "lebanon-visa",
  "linkedin",
  "macao-passport",
  "macao-visa",
  "malaysia-passport",
  "malaysia-visa",
  "mauritius-passport",
  "mexico-passport",
  "mexico-visa",
  "morocco-evisa",
  "morocco-passport",
  "morocco-visa",
  "myanmar-passport",
  "myanmar-visa",
  "neet-passport",
  "neet-postcard",
  "nepal-passport",
  "nepal-visa",
  "netherlands-driving-license",
  "netherlands-idcard",
  "netherlands-passport",
  "netherlands-visa",
  "newyork-gun-license",
  "newzealand-digital-passport",
  "newzealand-online-visa",
  "newzealand-paper-visa",
  "newzealand-passport",
  "newzealand-visa",
  "nigeria-passport",
  "nigeria-passport2",
  "nigeria-visa",
  "norway-passport",
  "norway-visa",
  "oman-passport",
  "oman-visa",
  "pakistan-passport",
  "pakistan-visa",
  "panama-passport",
  "panama-visa",
  "peru-passport",
  "philippines-passport",
  "philippines-visa",
  "poland-passport",
  "poland-visa",
  "portugal-passport",
  "portugal-visa",
  "riteaid-passport",
  "romania-passport",
  "romania-visa",
  "russia-passport",
  "russian-visa",
  "sat-id",
  "saudiarabia-evisa",
  "saudiarabia-passport",
  "saudiarabia-passport-200",
  "saudiarabia-visa",
  "schengen-visa",
  "singapore-passport",
  "singapore-pr",
  "singapore-visa",
  "southafrica-passport",
  "southafrica-visa",
  "southkorea-passport",
  "southkorea-visa",
  "spain-dni",
  "spain-passport",
  "spain-visa",
  "student-id-300x300px",
  "student-id-300x400px",
  "student-id-400x600px",
  "student-id-600x600px",
  "student-id-900x1200px",
  "sweden-passport",
  "sweden-visa",
  "sweden-work",
  "sweden-work-600-dpi",
  "switzerland-foreign-residence-permit",
  "switzerland-passport",
  "switzerland-visa",
  "syria-passport",
  "syria-visa",
  "taiwan-halfbody",
  "taiwan-idphoto",
  "taiwan-oneinch",
  "taiwan-oneinchhalfbody",
  "taiwan-passport",
  "taiwan-twoinch",
  "taiwan-visa",
  "tanzania-passport",
  "tanzania-visa",
  "texas-id",
  "thailand-passport",
  "thailand-visa",
  "theunitedarabemirates-passport",
  "theunitedarabemirates-visa",
  "trinidadandtobago-passport",
  "turkey-passport",
  "turkey-visa",
  "turkish-residence-card",
  "uae-driving-license",
  "uae-evisa",
  "uae-family-book",
  "uae-id-card",
  "uae-passport",
  "uae-register-arrival",
  "uae-residence",
  "uae-visa",
  "uganda-visa",
  "uk-baby-passport",
  "uk-bno-digital",
  "uk-bus-pass",
  "uk-citizencard",
  "uk-digital-passport",
  "uk-driverlicense",
  "uk-passport",
  "uk-provisional-driving-license",
  "uk-railcard",
  "uk-student-id-card",
  "uk-visa",
  "ukraine-passport",
  "ukraine-visa",
  "ups-passport",
  "us-dvlottery",
  "us-ead",
  "us-greencard",
  "us-nursing-license",
  "us-opt",
  "us-passport",
  "us-passport-card",
  "us-visa",
  "uscis-passport",
  "uzbekistan-passport",
  "uzbekistan-visa",
  "venezuela-passport",
  "venezuela-visa",
  "vietnam-evisa",
  "vietnam-passport",
  "vietnam-visa",
  "walgreen-passport",
  "zimbabwe-passport",
  "zimbabwe-visa",
] as const;
export type SpecCode = (typeof allSpecCodes)[number];

export function specCodeFromString(value: string): SpecCode | undefined {
  if (allSpecCodes.includes(value as SpecCode)) {
    return value as SpecCode;
  }
  return undefined;
}

export const allPhotoSpecs: Record<SpecCode, PhotoSpec> = {
  "1.5x1.5-inch": {
    specCode: "1.5x1.5-inch",
    specCodeInEnglish: "1.5x1.5 Inches (38x38 Milimetres)",
    headHeightText: "",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "in",
    widthPx: 450,
    widthUnit: 1.5,
    heightPx: 450,
    heightUnit: 1.5,
  },
  "1.5x2-inch": {
    specCode: "1.5x2-inch",
    specCodeInEnglish: "1.5x1.5 Inches (38x38 Milimetres)",
    headHeightText: "",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "in",
    widthPx: 450,
    widthUnit: 1.5,
    heightPx: 600,
    heightUnit: 2,
  },
  "1x1-inch": {
    specCode: "1x1-inch",
    specCodeInEnglish: "1x1 inch photo",
    headHeightText: "",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "in",
    widthPx: 300,
    widthUnit: 1,
    heightPx: 300,
    heightUnit: 1,
  },
  "20x30-mm": {
    specCode: "20x30-mm",
    specCodeInEnglish: "20x30 mm",
    headHeightText: "63 - 63",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 236,
    widthUnit: 20,
    heightPx: 354,
    heightUnit: 30,
  },
  "25x30-mm": {
    specCode: "25x30-mm",
    specCodeInEnglish: "25x30 mm",
    headHeightText: "75 - 75",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 295,
    widthUnit: 25,
    heightPx: 354,
    heightUnit: 30,
  },
  "25x35-mm": {
    specCode: "25x35-mm",
    specCodeInEnglish: "25x35 mm",
    headHeightText: "78.6 - 78.6",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 295,
    widthUnit: 25,
    heightPx: 413,
    heightUnit: 35,
  },
  "26x32-mm": {
    specCode: "26x32-mm",
    specCodeInEnglish: "26x32 mm",
    headHeightText: "73.4 - 73.4",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 307,
    widthUnit: 26,
    heightPx: 378,
    heightUnit: 32,
  },
  "2x2-inch": {
    specCode: "2x2-inch",
    specCodeInEnglish: "US Passport",
    headHeightText: "1 - 1 3/8",
    eyeToBottomText: "1 - 1 3/8",
    bgColorText: "white",
    dpi: 300,
    unit: "in",
    widthPx: 600,
    widthUnit: 2,
    heightPx: 600,
    heightUnit: 2,
  },
  "30x40-mm": {
    specCode: "30x40-mm",
    specCodeInEnglish: "30x40 mm",
    headHeightText: "75 - 75",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 354,
    widthUnit: 30,
    heightPx: 472,
    heightUnit: 40,
  },
  "33x48-mm": {
    specCode: "33x48-mm",
    specCodeInEnglish: "33x48 mm",
    headHeightText: "65.6 - 65.6",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 389,
    widthUnit: 33,
    heightPx: 566,
    heightUnit: 48,
  },
  "35x40-mm": {
    specCode: "35x40-mm",
    specCodeInEnglish: "35x40 mm",
    headHeightText: "75 - 75",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 413,
    widthUnit: 35,
    heightPx: 472,
    heightUnit: 40,
  },
  "35x45-mm": {
    specCode: "35x45-mm",
    specCodeInEnglish: "35x45 mm",
    headHeightText: "32 - 36",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 413,
    widthUnit: 35,
    heightPx: 531,
    heightUnit: 45,
  },
  "40x40-mm": {
    specCode: "40x40-mm",
    specCodeInEnglish: "40x40 mm",
    headHeightText: "70 - 70",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 472,
    widthUnit: 40,
    heightPx: 472,
    heightUnit: 40,
  },
  "40x50-mm": {
    specCode: "40x50-mm",
    specCodeInEnglish: "40x50 mm",
    headHeightText: "32 - 36",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 472,
    widthUnit: 40,
    heightPx: 590,
    heightUnit: 50,
  },
  "40x60-mm": {
    specCode: "40x60-mm",
    specCodeInEnglish: "40x60 mm",
    headHeightText: "60 - 60",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 472,
    widthUnit: 40,
    heightPx: 708,
    heightUnit: 60,
  },
  "50x50-mm": {
    specCode: "50x50-mm",
    specCodeInEnglish: "50x50 mm",
    headHeightText: "68 - 68",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 590,
    widthUnit: 50,
    heightPx: 590,
    heightUnit: 50,
  },
  "50x70-mm": {
    specCode: "50x70-mm",
    specCodeInEnglish: "50x70 mm",
    headHeightText: "60 - 60",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 590,
    widthUnit: 50,
    heightPx: 826,
    heightUnit: 70,
  },
  "51x70-mm": {
    specCode: "51x70-mm",
    specCodeInEnglish: "51x70 mm",
    headHeightText: "61.8 - 61.8",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 602,
    widthUnit: 51,
    heightPx: 826,
    heightUnit: 70,
  },
  "albania-passport": {
    specCode: "albania-passport",
    specCodeInEnglish: "Albania Passport",
    headHeightText: "32 - 36",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 900,
    widthUnit: 40,
    heightPx: 1200,
    heightUnit: 50,
  },
  "argentina-passport": {
    specCode: "argentina-passport",
    specCodeInEnglish: "Argentina Passport",
    headHeightText: "24 - 28",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "in",
    widthPx: 900,
    widthUnit: 1.5,
    heightPx: 900,
    heightUnit: 1.5,
  },
  "argentina-visa": {
    specCode: "argentina-visa",
    specCodeInEnglish: "Argentina VISA",
    headHeightText: "28 - 32",
    eyeToBottomText: "",
    bgColorText: "blue",
    dpi: 300,
    unit: "mm",
    widthPx: 900,
    widthUnit: 40,
    heightPx: 900,
    heightUnit: 40,
  },
  "australia-baby-passport": {
    specCode: "australia-baby-passport",
    specCodeInEnglish: "Australian Baby Passport",
    headHeightText: "32 - 36",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 413,
    widthUnit: 35,
    heightPx: 531,
    heightUnit: 45,
  },
  "australia-nsw-driving-license": {
    specCode: "australia-nsw-driving-license",
    specCodeInEnglish: "NSW Driving License",
    headHeightText: "32 - 36",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 413,
    widthUnit: 35,
    heightPx: 531,
    heightUnit: 45,
  },
  "australia-passport": {
    specCode: "australia-passport",
    specCodeInEnglish: "Australia Passport",
    headHeightText: "32 - 36",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 413,
    widthUnit: 35,
    heightPx: 531,
    heightUnit: 45,
  },
  "australia-proof-of-age-card": {
    specCode: "australia-proof-of-age-card",
    specCodeInEnglish: "Proof of Age Card",
    headHeightText: "32 - 36",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 413,
    widthUnit: 35,
    heightPx: 531,
    heightUnit: 45,
  },
  "australia-queensland-driving-license": {
    specCode: "australia-queensland-driving-license",
    specCodeInEnglish: "Australia Queensland Driving License",
    headHeightText: "32 - 36",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 413,
    widthUnit: 35,
    heightPx: 531,
    heightUnit: 45,
  },
  "australia-visa": {
    specCode: "australia-visa",
    specCodeInEnglish: "Australia VISA",
    headHeightText: "32 - 36",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 413,
    widthUnit: 35,
    heightPx: 531,
    heightUnit: 45,
  },
  "baby-passport": {
    specCode: "baby-passport",
    specCodeInEnglish: "Baby Passport",
    headHeightText: "1 - 1 3/8",
    eyeToBottomText: "1 - 1 3/8",
    bgColorText: "white",
    dpi: 300,
    unit: "in",
    widthPx: 600,
    widthUnit: 2,
    heightPx: 600,
    heightUnit: 2,
  },
  "bahrain-passport": {
    specCode: "bahrain-passport",
    specCodeInEnglish: "Bahrain Passport",
    headHeightText: "42 - 48",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 945,
    widthUnit: 40,
    heightPx: 1417,
    heightUnit: 60,
  },
  "bahrain-visa": {
    specCode: "bahrain-visa",
    specCodeInEnglish: "Bahrain VISA",
    headHeightText: "42 - 48",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 945,
    widthUnit: 40,
    heightPx: 1417,
    heightUnit: 60,
  },
  "bangladesh-passport": {
    specCode: "bangladesh-passport",
    specCodeInEnglish: "Bangladesh Passport",
    headHeightText: "32 - 36",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 531,
    widthUnit: 45,
    heightPx: 650,
    heightUnit: 55,
  },
  "bangladesh-visa": {
    specCode: "bangladesh-visa",
    specCodeInEnglish: "Bangladesh VISA",
    headHeightText: "32 - 36",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 413,
    widthUnit: 35,
    heightPx: 531,
    heightUnit: 45,
  },
  "belarus-passport": {
    specCode: "belarus-passport",
    specCodeInEnglish: "Belarus Passport",
    headHeightText: "32 - 35",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 944,
    widthUnit: 40,
    heightPx: 1180,
    heightUnit: 50,
  },
  "belarus-visa": {
    specCode: "belarus-visa",
    specCodeInEnglish: "Belarus VISA",
    headHeightText: "32 - 36",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 413,
    widthUnit: 35,
    heightPx: 531,
    heightUnit: 45,
  },
  "belgium-passport": {
    specCode: "belgium-passport",
    specCodeInEnglish: "Belgium Passport",
    headHeightText: "31 - 36",
    eyeToBottomText: "20 - 30",
    bgColorText: "grey",
    dpi: 300,
    unit: "mm",
    widthPx: 413,
    widthUnit: 35,
    heightPx: 531,
    heightUnit: 45,
  },
  "brazil-cnh": {
    specCode: "brazil-cnh",
    specCodeInEnglish: "CNH",
    headHeightText: "28 - 32",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 354,
    widthUnit: 30,
    heightPx: 472,
    heightUnit: 40,
  },
  "brazil-id": {
    specCode: "brazil-id",
    specCodeInEnglish: "Brazil ID",
    headHeightText: "28 - 32",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 708,
    widthUnit: 30,
    heightPx: 944,
    heightUnit: 40,
  },
  "brazil-passport": {
    specCode: "brazil-passport",
    specCodeInEnglish: "Brazil Passport(51*51mm)",
    headHeightText: "1 - 1 3/8",
    eyeToBottomText: "1 - 1 3/8",
    bgColorText: "white",
    dpi: 300,
    unit: "in",
    widthPx: 600,
    widthUnit: 2,
    heightPx: 600,
    heightUnit: 2,
  },
  "brazil-passport-old-standard": {
    specCode: "brazil-passport-old-standard",
    specCodeInEnglish: "Brazil Passport(Old Standard)",
    headHeightText: "49 - 56",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 590,
    widthUnit: 50,
    heightPx: 826,
    heightUnit: 70,
  },
  "brazil-visa": {
    specCode: "brazil-visa",
    specCodeInEnglish: "Brazil Visa",
    headHeightText: "32-36",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 413,
    widthUnit: 35,
    heightPx: 531,
    heightUnit: 45,
  },
  "brazil-work": {
    specCode: "brazil-work",
    specCodeInEnglish: "Carteira de Trabalho",
    headHeightText: "28 - 32",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 354,
    widthUnit: 30,
    heightPx: 472,
    heightUnit: 40,
  },
  "bulgaria-passport": {
    specCode: "bulgaria-passport",
    specCodeInEnglish: "Bulgaria Passport",
    headHeightText: "31 - 36",
    eyeToBottomText: "20 - 30",
    bgColorText: "grey",
    dpi: 300,
    unit: "mm",
    widthPx: 413,
    widthUnit: 35,
    heightPx: 531,
    heightUnit: 45,
  },
  "bulgaria-visa": {
    specCode: "bulgaria-visa",
    specCodeInEnglish: "Bulgaria VISA",
    headHeightText: "31 - 36",
    eyeToBottomText: "20 - 30",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 413,
    widthUnit: 35,
    heightPx: 531,
    heightUnit: 45,
  },
  "cambodia-passport": {
    specCode: "cambodia-passport",
    specCodeInEnglish: "Cambodia Passport",
    headHeightText: "32 - 36",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 413,
    widthUnit: 35,
    heightPx: 531,
    heightUnit: 45,
  },
  "cambodia-visa": {
    specCode: "cambodia-visa",
    specCodeInEnglish: "Cambodia VISA",
    headHeightText: "32 - 36",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 413,
    widthUnit: 35,
    heightPx: 531,
    heightUnit: 45,
  },
  "canada-baby-passport": {
    specCode: "canada-baby-passport",
    specCodeInEnglish: "Canada Baby Passport",
    headHeightText: "44.3 - 51.4",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 590,
    widthUnit: 50,
    heightPx: 826,
    heightUnit: 70,
  },
  "canada-citizenship": {
    specCode: "canada-citizenship",
    specCodeInEnglish: "Canada Citizenship",
    headHeightText: "44.3 - 51.4",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 590,
    widthUnit: 50,
    heightPx: 826,
    heightUnit: 70,
  },
  "canada-firearms-license": {
    specCode: "canada-firearms-license",
    specCodeInEnglish: "Canadian Firearms License",
    headHeightText: "78 - 53",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 531,
    widthUnit: 45,
    heightPx: 673,
    heightUnit: 57,
  },
  "canada-passport": {
    specCode: "canada-passport",
    specCodeInEnglish: "Canada Passport Photo",
    headHeightText: "32 - 36",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 590,
    widthUnit: 50,
    heightPx: 826,
    heightUnit: 70,
  },
  "canada-permanent-residence": {
    specCode: "canada-permanent-residence",
    specCodeInEnglish: "Canada Permanent Residence",
    headHeightText: "31-36",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 600,
    unit: "mm",
    widthPx: 590,
    widthUnit: 50,
    heightPx: 826,
    heightUnit: 70,
  },
  "canada-permanent-resident-card": {
    specCode: "canada-permanent-resident-card",
    specCodeInEnglish: "Permanent Resident Card",
    headHeightText: "44.3 - 51.4",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 590,
    widthUnit: 50,
    heightPx: 826,
    heightUnit: 70,
  },
  "canada-temporary-residence-permit": {
    specCode: "canada-temporary-residence-permit",
    specCodeInEnglish: "Temporary Residence Permit Canada",
    headHeightText: "68.9 - 80",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 413,
    widthUnit: 35,
    heightPx: 531,
    heightUnit: 45,
  },
  "canada-visa": {
    specCode: "canada-visa",
    specCodeInEnglish: "Canada VISA",
    headHeightText: "31 - 36",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 413,
    widthUnit: 35,
    heightPx: 531,
    heightUnit: 45,
  },
  "chile-visa": {
    specCode: "chile-visa",
    specCodeInEnglish: "Chile Visa",
    headHeightText: "68.9 - 80",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 413,
    widthUnit: 35,
    heightPx: 531,
    heightUnit: 45,
  },
  "china-passport": {
    specCode: "china-passport",
    specCodeInEnglish: "China Passport",
    headHeightText: "28 - 33",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 600,
    unit: "mm",
    widthPx: 388,
    widthUnit: 33,
    heightPx: 564,
    heightUnit: 48,
  },
  "china-taiwan": {
    specCode: "china-taiwan",
    specCodeInEnglish: "Taiwan Compatriot Permit",
    headHeightText: "32 - 36",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 413,
    widthUnit: 35,
    heightPx: 531,
    heightUnit: 45,
  },
  "china-visa": {
    specCode: "china-visa",
    specCodeInEnglish: "China VISA",
    headHeightText: "28 - 33",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 388,
    widthUnit: 33,
    heightPx: 564,
    heightUnit: 48,
  },
  "colombia-passport": {
    specCode: "colombia-passport",
    specCodeInEnglish: "Colombia Passport",
    headHeightText: "1 3/8 - 2",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "in",
    widthPx: 600,
    widthUnit: 1.5,
    heightPx: 600,
    heightUnit: 2.5,
  },
  "colombia-visa": {
    specCode: "colombia-visa",
    specCodeInEnglish: "Colombia VISA",
    headHeightText: "28 - 32",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 708,
    widthUnit: 30,
    heightPx: 944,
    heightUnit: 40,
  },
  "costarica-passport": {
    specCode: "costarica-passport",
    specCodeInEnglish: "Costa Rica Passpot",
    headHeightText: "32 - 36",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 413,
    widthUnit: 35,
    heightPx: 531,
    heightUnit: 45,
  },
  "costco-passport": {
    specCode: "costco-passport",
    specCodeInEnglish: "Costco Passport",
    headHeightText: "1 - 1 3/8",
    eyeToBottomText: "1 - 1 3/8",
    bgColorText: "white",
    dpi: 300,
    unit: "in",
    widthPx: 600,
    widthUnit: 2,
    heightPx: 600,
    heightUnit: 2,
  },
  "croatia-passport": {
    specCode: "croatia-passport",
    specCodeInEnglish: "Croatia Passport",
    headHeightText: "31 - 36",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 413,
    widthUnit: 35,
    heightPx: 531,
    heightUnit: 45,
  },
  "cuba-passport": {
    specCode: "cuba-passport",
    specCodeInEnglish: "Cuba Passport",
    headHeightText: "1 - 1 3/8",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "in",
    widthPx: 600,
    widthUnit: 2,
    heightPx: 600,
    heightUnit: 2,
  },
  "cuba-visa": {
    specCode: "cuba-visa",
    specCodeInEnglish: "Cuba VISA",
    headHeightText: "1 - 1 3/8",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "in",
    widthPx: 600,
    widthUnit: 2,
    heightPx: 600,
    heightUnit: 2,
  },
  "cvs-passport": {
    specCode: "cvs-passport",
    specCodeInEnglish: "CVS Passport",
    headHeightText: "1 - 1 3/8",
    eyeToBottomText: "1 - 1 3/8",
    bgColorText: "white",
    dpi: 300,
    unit: "in",
    widthPx: 600,
    widthUnit: 2,
    heightPx: 600,
    heightUnit: 2,
  },
  "cyprus-passport": {
    specCode: "cyprus-passport",
    specCodeInEnglish: "Cyprus Passport",
    headHeightText: "35 - 40",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 944,
    widthUnit: 40,
    heightPx: 1181,
    heightUnit: 50,
  },
  "cyprus-visa": {
    specCode: "cyprus-visa",
    specCodeInEnglish: "Cyprus-VISA",
    headHeightText: "31 - 36",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 413,
    widthUnit: 35,
    heightPx: 531,
    heightUnit: 45,
  },
  "czechrepublic-passport": {
    specCode: "czechrepublic-passport",
    specCodeInEnglish: "Czech Republic Passport",
    headHeightText: "31 - 36",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 413,
    widthUnit: 35,
    heightPx: 531,
    heightUnit: 45,
  },
  "czechrepublic-visa": {
    specCode: "czechrepublic-visa",
    specCodeInEnglish: "Czechrepublic VISA",
    headHeightText: "31 - 36",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 413,
    widthUnit: 35,
    heightPx: 531,
    heightUnit: 45,
  },
  "denmark-passport": {
    specCode: "denmark-passport",
    specCodeInEnglish: "Denmark Passport",
    headHeightText: "32 - 36",
    eyeToBottomText: "20 - 30",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 413,
    widthUnit: 35,
    heightPx: 531,
    heightUnit: 45,
  },
  "dubai-evisa": {
    specCode: "dubai-evisa",
    specCodeInEnglish: "UAE eVISA",
    headHeightText: "265.68 - 265.68",
    eyeToBottomText: "20 - 30",
    bgColorText: "white",
    dpi: 300,
    unit: "px",
    widthPx: 300,
    widthUnit: 300,
    heightPx: 369,
    heightUnit: 369,
  },
  "dubai-visa": {
    specCode: "dubai-visa",
    specCodeInEnglish: "UAE VISA",
    headHeightText: "38.5 - 41.25",
    eyeToBottomText: "20 - 30",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 507,
    widthUnit: 43,
    heightPx: 649,
    heightUnit: 55,
  },
  "dutch-passport": {
    specCode: "dutch-passport",
    specCodeInEnglish: "Dutch Passport",
    headHeightText: "26 - 30",
    eyeToBottomText: "",
    bgColorText: "grey",
    dpi: 300,
    unit: "mm",
    widthPx: 413,
    widthUnit: 35,
    heightPx: 531,
    heightUnit: 45,
  },
  "egypt-passport": {
    specCode: "egypt-passport",
    specCodeInEnglish: "Egyptian Passport",
    headHeightText: "70 - 80",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 472,
    widthUnit: 40,
    heightPx: 708,
    heightUnit: 60,
  },
  "esn-card-photo-for-turku-exchange-student": {
    specCode: "esn-card-photo-for-turku-exchange-student",
    specCodeInEnglish: "ESN Card for Turku Exchange Students",
    headHeightText: "75 - 75",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 319,
    widthUnit: 27,
    heightPx: 437,
    heightUnit: 37,
  },
  "estonia-passport": {
    specCode: "estonia-passport",
    specCodeInEnglish: "Estonia Passport",
    headHeightText: "35 - 40",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 1300,
    widthUnit: 40,
    heightPx: 1600,
    heightUnit: 50,
  },
  "estonia-visa": {
    specCode: "estonia-visa",
    specCodeInEnglish: "Estonia VISA",
    headHeightText: "31 - 36",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 413,
    widthUnit: 35,
    heightPx: 531,
    heightUnit: 45,
  },
  "european-athletics": {
    specCode: "european-athletics",
    specCodeInEnglish: "European Athletics",
    headHeightText: "26 - 30",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 354,
    widthUnit: 30,
    heightPx: 472,
    heightUnit: 40,
  },
  "europeanunion-passport": {
    specCode: "europeanunion-passport",
    specCodeInEnglish: "European Union(EU) Passport",
    headHeightText: "32 - 36",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 413,
    widthUnit: 35,
    heightPx: 531,
    heightUnit: 45,
  },
  "europeanunion-visa": {
    specCode: "europeanunion-visa",
    specCodeInEnglish: "European Union(EU) VISA",
    headHeightText: "32 - 36",
    eyeToBottomText: "",
    bgColorText: "grey",
    dpi: 300,
    unit: "mm",
    widthPx: 413,
    widthUnit: 35,
    heightPx: 531,
    heightUnit: 45,
  },
  "fedex-passport": {
    specCode: "fedex-passport",
    specCodeInEnglish: "Fedex Passport",
    headHeightText: "1 - 1 3/8",
    eyeToBottomText: "1 - 1 3/8",
    bgColorText: "white",
    dpi: 300,
    unit: "in",
    widthPx: 600,
    widthUnit: 2,
    heightPx: 600,
    heightUnit: 2,
  },
  "finland-digital-passport": {
    specCode: "finland-digital-passport",
    specCodeInEnglish: "Finland Digital Passport",
    headHeightText: "445 - 500",
    eyeToBottomText: "",
    bgColorText: "grey",
    dpi: 300,
    unit: "px",
    widthPx: 500,
    widthUnit: 500,
    heightPx: 653,
    heightUnit: 653,
  },
  "finland-driving-license": {
    specCode: "finland-driving-license",
    specCodeInEnglish: "Finland Driving License",
    headHeightText: "32 - 36",
    eyeToBottomText: "",
    bgColorText: "grey",
    dpi: 300,
    unit: "mm",
    widthPx: 500,
    widthUnit: 36,
    heightPx: 653,
    heightUnit: 47,
  },
  "finland-idcard": {
    specCode: "finland-idcard",
    specCodeInEnglish: "Finland Identity Card",
    headHeightText: "32 - 36",
    eyeToBottomText: "",
    bgColorText: "grey",
    dpi: 300,
    unit: "mm",
    widthPx: 500,
    widthUnit: 36,
    heightPx: 653,
    heightUnit: 47,
  },
  "finland-passport": {
    specCode: "finland-passport",
    specCodeInEnglish: "Finland Passport",
    headHeightText: "32 - 36",
    eyeToBottomText: "",
    bgColorText: "grey",
    dpi: 300,
    unit: "mm",
    widthPx: 500,
    widthUnit: 36,
    heightPx: 653,
    heightUnit: 47,
  },
  "finland-passport2": {
    specCode: "finland-passport2",
    specCodeInEnglish: "Finland Passport(Under 11)",
    headHeightText: "25 - 36",
    eyeToBottomText: "",
    bgColorText: "grey",
    dpi: 300,
    unit: "mm",
    widthPx: 500,
    widthUnit: 36,
    heightPx: 653,
    heightUnit: 47,
  },
  "finland-visa": {
    specCode: "finland-visa",
    specCodeInEnglish: "Finland VISA",
    headHeightText: "32 - 36",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 500,
    widthUnit: 36,
    heightPx: 653,
    heightUnit: 47,
  },
  "football-player": {
    specCode: "football-player",
    specCodeInEnglish: "Germany Passport",
    headHeightText: "32 - 36",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 450,
    widthUnit: 35,
    heightPx: 530,
    heightUnit: 45,
  },
  "foto-25x30": {
    specCode: "foto-25x30",
    specCodeInEnglish: "Foto 2.5x3 (25x30 mm)",
    headHeightText: "70 - 80",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 600,
    unit: "mm",
    widthPx: 590,
    widthUnit: 25,
    heightPx: 708,
    heightUnit: 30,
  },
  "foto-2x2": {
    specCode: "foto-2x2",
    specCodeInEnglish: "US Passport",
    headHeightText: "1 - 1 3/8",
    eyeToBottomText: "1 1/8 - 1 3/8",
    bgColorText: "white",
    dpi: 300,
    unit: "in",
    widthPx: 600,
    widthUnit: 2,
    heightPx: 600,
    heightUnit: 2,
  },
  "foto-35x45": {
    specCode: "foto-35x45",
    specCodeInEnglish: "Foto 35x45(3.5*4.5cm)",
    headHeightText: "31 - 36",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 600,
    unit: "mm",
    widthPx: 826,
    widthUnit: 35,
    heightPx: 1062,
    heightUnit: 45,
  },
  "foto-3x4": {
    specCode: "foto-3x4",
    specCodeInEnglish: "Foto 3x4",
    headHeightText: "20 - 24",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 600,
    unit: "mm",
    widthPx: 708,
    widthUnit: 30,
    heightPx: 944,
    heightUnit: 40,
  },
  "foto-4x5": {
    specCode: "foto-4x5",
    specCodeInEnglish: "Foto 4x5 (4x5 cm)",
    headHeightText: "70 - 80",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 600,
    unit: "mm",
    widthPx: 944,
    widthUnit: 40,
    heightPx: 1180,
    heightUnit: 50,
  },
  "foto-5x7": {
    specCode: "foto-5x7",
    specCodeInEnglish: "Foto 5x7(5*7cm)",
    headHeightText: "49 - 56",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 600,
    unit: "mm",
    widthPx: 1180,
    widthUnit: 50,
    heightPx: 1652,
    heightUnit: 70,
  },
  "france-carte-vitale": {
    specCode: "france-carte-vitale",
    specCodeInEnglish: "France Carte Vitale",
    headHeightText: "35 - 45",
    eyeToBottomText: "",
    bgColorText: "grey",
    dpi: 300,
    unit: "mm",
    widthPx: 413,
    widthUnit: 35,
    heightPx: 531,
    heightUnit: 45,
  },
  "france-passport": {
    specCode: "france-passport",
    specCodeInEnglish: "France Passport",
    headHeightText: "32 - 36",
    eyeToBottomText: "20 - 30",
    bgColorText: "grey",
    dpi: 300,
    unit: "mm",
    widthPx: 413,
    widthUnit: 35,
    heightPx: 531,
    heightUnit: 45,
  },
  "france-visa": {
    specCode: "france-visa",
    specCodeInEnglish: "France Visa",
    headHeightText: "32 - 36",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 413,
    widthUnit: 35,
    heightPx: 531,
    heightUnit: 45,
  },
  "franch-driver ": {
    specCode: "franch-driver ",
    specCodeInEnglish: "Franch Driver License",
    headHeightText: "35 - 45",
    eyeToBottomText: "",
    bgColorText: "grey",
    dpi: 0,
    unit: "mm",
    widthPx: 413,
    widthUnit: 35,
    heightPx: 531,
    heightUnit: 45,
  },
  "franch-id-card": {
    specCode: "franch-id-card",
    specCodeInEnglish: "Franch ID Card",
    headHeightText: "35 - 45",
    eyeToBottomText: "",
    bgColorText: "grey",
    dpi: 300,
    unit: "mm",
    widthPx: 413,
    widthUnit: 35,
    heightPx: 531,
    heightUnit: 45,
  },
  "french-passport": {
    specCode: "french-passport",
    specCodeInEnglish: "French Passport",
    headHeightText: "35 - 45",
    eyeToBottomText: "",
    bgColorText: "grey",
    dpi: 300,
    unit: "mm",
    widthPx: 413,
    widthUnit: 35,
    heightPx: 531,
    heightUnit: 45,
  },
  "germany-disability-card": {
    specCode: "germany-disability-card",
    specCodeInEnglish: "Germany Disability Card Photo",
    headHeightText: "32 - 36",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 413,
    widthUnit: 35,
    heightPx: 531,
    heightUnit: 45,
  },
  "germany-driving-license": {
    specCode: "germany-driving-license",
    specCodeInEnglish: "Germany Driving License",
    headHeightText: "32 - 36",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 413,
    widthUnit: 35,
    heightPx: 531,
    heightUnit: 45,
  },
  "germany-health-insurance-card": {
    specCode: "germany-health-insurance-card",
    specCodeInEnglish: "Germany Health Insurance Card",
    headHeightText: "32 - 36",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 413,
    widthUnit: 35,
    heightPx: 531,
    heightUnit: 45,
  },
  "germany-id": {
    specCode: "germany-id",
    specCodeInEnglish: "Germany ID card",
    headHeightText: "32 - 36",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 413,
    widthUnit: 35,
    heightPx: 531,
    heightUnit: 45,
  },
  "germany-passport": {
    specCode: "germany-passport",
    specCodeInEnglish: "Germany Passport",
    headHeightText: "32 - 36",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 413,
    widthUnit: 35,
    heightPx: 531,
    heightUnit: 45,
  },
  "germany-permanent-residence": {
    specCode: "germany-permanent-residence",
    specCodeInEnglish: "German Permanent Residence",
    headHeightText: "76.7 - 76.7",
    eyeToBottomText: "",
    bgColorText: "off white",
    dpi: 300,
    unit: "mm",
    widthPx: 413,
    widthUnit: 35,
    heightPx: 531,
    heightUnit: 45,
  },
  "germany-rail-card": {
    specCode: "germany-rail-card",
    specCodeInEnglish: "Germany Rail Card Photo",
    headHeightText: "32 - 36",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 413,
    widthUnit: 35,
    heightPx: 531,
    heightUnit: 45,
  },
  "germany-residence-permit": {
    specCode: "germany-residence-permit",
    specCodeInEnglish: "Germany Residence Permit",
    headHeightText: "32 - 36",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 413,
    widthUnit: 35,
    heightPx: 531,
    heightUnit: 45,
  },
  "germany-resume": {
    specCode: "germany-resume",
    specCodeInEnglish: "Germany Resume Photo",
    headHeightText: "32 - 36",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 413,
    widthUnit: 35,
    heightPx: 531,
    heightUnit: 45,
  },
  "germany-visa": {
    specCode: "germany-visa",
    specCodeInEnglish: "Germany VISA",
    headHeightText: "32 - 36",
    eyeToBottomText: "",
    bgColorText: "grey",
    dpi: 300,
    unit: "mm",
    widthPx: 413,
    widthUnit: 35,
    heightPx: 531,
    heightUnit: 45,
  },
  "ghana-passport": {
    specCode: "ghana-passport",
    specCodeInEnglish: "Ghana Passport",
    headHeightText: "32 - 36",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 413,
    widthUnit: 35,
    heightPx: 531,
    heightUnit: 45,
  },
  "ghana-visa": {
    specCode: "ghana-visa",
    specCodeInEnglish: "Ghana VISA",
    headHeightText: "32 - 36",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 413,
    widthUnit: 35,
    heightPx: 531,
    heightUnit: 45,
  },
  "ghana-visa1": {
    specCode: "ghana-visa1",
    specCodeInEnglish: "Ghana VISA",
    headHeightText: "32 - 36",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 413,
    widthUnit: 35,
    heightPx: 531,
    heightUnit: 45,
  },
  "greece-passport": {
    specCode: "greece-passport",
    specCodeInEnglish: "Greece Passport",
    headHeightText: "31 - 35",
    eyeToBottomText: "30 - 39",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 1300,
    widthUnit: 40,
    heightPx: 1600,
    heightUnit: 60,
  },
  "greece-visa": {
    specCode: "greece-visa",
    specCodeInEnglish: "Greece VISA",
    headHeightText: "31 - 36",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 827,
    widthUnit: 35,
    heightPx: 1063,
    heightUnit: 45,
  },
  "hayya-card": {
    specCode: "hayya-card",
    specCodeInEnglish: "Hayya Card",
    headHeightText: "66.7 - 66.7",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 354,
    widthUnit: 30,
    heightPx: 472,
    heightUnit: 40,
  },
  "hk-china-permit-multiple": {
    specCode: "hk-china-permit-multiple",
    specCodeInEnglish: "China VISA",
    headHeightText: "28 - 33",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 388,
    widthUnit: 33,
    heightPx: 564,
    heightUnit: 48,
  },
  "hk-china-permit-single": {
    specCode: "hk-china-permit-single",
    specCodeInEnglish: "China VISA",
    headHeightText: "28 - 33",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 388,
    widthUnit: 33,
    heightPx: 564,
    heightUnit: 48,
  },
  "hk-passport-digital": {
    specCode: "hk-passport-digital",
    specCodeInEnglish: "Hong Kong Passport",
    headHeightText: "32 - 36",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 1200,
    widthUnit: 50,
    heightPx: 1600,
    heightUnit: 40,
  },
  "hungary-passport": {
    specCode: "hungary-passport",
    specCodeInEnglish: "Hungary Passport",
    headHeightText: "31 - 36",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 826,
    widthUnit: 35,
    heightPx: 1062,
    heightUnit: 45,
  },
  "hungary-visa": {
    specCode: "hungary-visa",
    specCodeInEnglish: "Hungary VISA",
    headHeightText: "32 - 36",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 826,
    widthUnit: 35,
    heightPx: 1062,
    heightUnit: 45,
  },
  "illinois-foid": {
    specCode: "illinois-foid",
    specCodeInEnglish: "Firearm Owners Identification (FOID)",
    headHeightText: "1 - 1 3/8",
    eyeToBottomText: "1 - 1 3/8",
    bgColorText: "white",
    dpi: 300,
    unit: "in",
    widthPx: 600,
    widthUnit: 2,
    heightPx: 600,
    heightUnit: 2,
  },
  "india-evisa-350": {
    specCode: "india-evisa-350",
    specCodeInEnglish: "India eVISA(350x350px)",
    headHeightText: "1 - 1 3/8",
    eyeToBottomText: "1 - 1 3/8",
    bgColorText: "white",
    dpi: 300,
    unit: "in",
    widthPx: 350,
    widthUnit: 2,
    heightPx: 350,
    heightUnit: 2,
  },
  "india-oci": {
    specCode: "india-oci",
    specCodeInEnglish: "India Overseas Citizenship",
    headHeightText: "1- 1 3/8",
    eyeToBottomText: "1-1 3/8",
    bgColorText: "white",
    dpi: 300,
    unit: "in",
    widthPx: 600,
    widthUnit: 2,
    heightPx: 600,
    heightUnit: 2,
  },
  "india-passport": {
    specCode: "india-passport",
    specCodeInEnglish: "India Passport",
    headHeightText: "1 - 1 3/8",
    eyeToBottomText: "1 - 1 3/8",
    bgColorText: "white",
    dpi: 300,
    unit: "in",
    widthPx: 600,
    widthUnit: 2,
    heightPx: 600,
    heightUnit: 2,
  },
  "india-visa": {
    specCode: "india-visa",
    specCodeInEnglish: "India VISA",
    headHeightText: "1 - 1 3/8",
    eyeToBottomText: "1 - 1 3/8",
    bgColorText: "white",
    dpi: 300,
    unit: "in",
    widthPx: 600,
    widthUnit: 2,
    heightPx: 600,
    heightUnit: 2,
  },
  "india-visa-2x2-inch": {
    specCode: "india-visa-2x2-inch",
    specCodeInEnglish: "India Visa 2x2 Inches",
    headHeightText: "1 - 1 3/8",
    eyeToBottomText: "1 1/8 - 1 3/8",
    bgColorText: "white",
    dpi: 300,
    unit: "in",
    widthPx: 600,
    widthUnit: 2,
    heightPx: 600,
    heightUnit: 2,
  },
  "indonesia-passport": {
    specCode: "indonesia-passport",
    specCodeInEnglish: "Indonesia Passport",
    headHeightText: "1 - 1 3/8",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "in",
    widthPx: 600,
    widthUnit: 2,
    heightPx: 600,
    heightUnit: 2,
  },
  "indonesia-visa": {
    specCode: "indonesia-visa",
    specCodeInEnglish: "Indonesia VISA",
    headHeightText: "32 - 36",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 413,
    widthUnit: 35,
    heightPx: 531,
    heightUnit: 45,
  },
  "iran-passport": {
    specCode: "iran-passport",
    specCodeInEnglish: "Iran Passport",
    headHeightText: "28 - 32",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 708,
    widthUnit: 30,
    heightPx: 944,
    heightUnit: 40,
  },
  "iran-visa": {
    specCode: "iran-visa",
    specCodeInEnglish: "Iran VISA",
    headHeightText: "32 - 36",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 413,
    widthUnit: 35,
    heightPx: 531,
    heightUnit: 45,
  },
  "ireland-digital-passport": {
    specCode: "ireland-digital-passport",
    specCodeInEnglish: "Ireland Digital Passport",
    headHeightText: "740-845",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 600,
    unit: "px",
    widthPx: 715,
    widthUnit: 715,
    heightPx: 951,
    heightUnit: 951,
  },
  "ireland-driverlicense": {
    specCode: "ireland-driverlicense",
    specCodeInEnglish: "Ireland Driver License",
    headHeightText: "32 - 36",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 413,
    widthUnit: 35,
    heightPx: 531,
    heightUnit: 45,
  },
  "ireland-passport": {
    specCode: "ireland-passport",
    specCodeInEnglish: "Ireland Passport(35*45mm)",
    headHeightText: "35 - 40",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 413,
    widthUnit: 35,
    heightPx: 531,
    heightUnit: 45,
  },
  "ireland-visa": {
    specCode: "ireland-visa",
    specCodeInEnglish: "Ireland VISA",
    headHeightText: "35 - 40",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 413,
    widthUnit: 35,
    heightPx: 531,
    heightUnit: 45,
  },
  "isic-card": {
    specCode: "isic-card",
    specCodeInEnglish: "ISIC Card (International Student Identity Card)",
    headHeightText: "32 - 36",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 413,
    widthUnit: 35,
    heightPx: 531,
    heightUnit: 45,
  },
  "israel-passport": {
    specCode: "israel-passport",
    specCodeInEnglish: "Israel Passport 35*45CM",
    headHeightText: "32 - 36",
    eyeToBottomText: "",
    bgColorText: "grey",
    dpi: 300,
    unit: "mm",
    widthPx: 413,
    widthUnit: 35,
    heightPx: 531,
    heightUnit: 45,
  },
  "israel-visa": {
    specCode: "israel-visa",
    specCodeInEnglish: "Israel VISA",
    headHeightText: "25 - 35",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 1000,
    widthUnit: 50,
    heightPx: 1000,
    heightUnit: 45,
  },
  "italy-passport": {
    specCode: "italy-passport",
    specCodeInEnglish: "Italy Passport",
    headHeightText: "32 - 36",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 413,
    widthUnit: 35,
    heightPx: 531,
    heightUnit: 45,
  },
  "italy-visa": {
    specCode: "italy-visa",
    specCodeInEnglish: "Italy VISA",
    headHeightText: "32 - 36",
    eyeToBottomText: "20 - 30",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 413,
    widthUnit: 35,
    heightPx: 531,
    heightUnit: 45,
  },
  "jamaica-passport": {
    specCode: "jamaica-passport",
    specCodeInEnglish: "Jamaica passport for Applicants with grey/white hair",
    headHeightText: "25 - 35",
    eyeToBottomText: "",
    bgColorText: "blue",
    dpi: 300,
    unit: "mm",
    widthPx: 413,
    widthUnit: 35,
    heightPx: 531,
    heightUnit: 45,
  },
  "jamaica-visa": {
    specCode: "jamaica-visa",
    specCodeInEnglish: "Jamaica VISA",
    headHeightText: "25 - 35",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 413,
    widthUnit: 35,
    heightPx: 531,
    heightUnit: 45,
  },
  "japan-driverlicense": {
    specCode: "japan-driverlicense",
    specCodeInEnglish: "Japan Driver License",
    headHeightText: "",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 283,
    widthUnit: 24,
    heightPx: 354,
    heightUnit: 30,
  },
  "japan-english": {
    specCode: "japan-english",
    specCodeInEnglish: "Japan English Test",
    headHeightText: "",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 283,
    widthUnit: 24,
    heightPx: 354,
    heightUnit: 30,
  },
  "japan-id": {
    specCode: "japan-id",
    specCodeInEnglish: "Japan ID",
    headHeightText: "32 - 36",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 413,
    widthUnit: 35,
    heightPx: 531,
    heightUnit: 45,
  },
  "japan-my-number": {
    specCode: "japan-my-number",
    specCodeInEnglish: "Japan My Number",
    headHeightText: "32 - 36",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 413,
    widthUnit: 35,
    heightPx: 531,
    heightUnit: 45,
  },
  "japan-passport": {
    specCode: "japan-passport",
    specCodeInEnglish: "Japan Passport",
    headHeightText: "32 - 36",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 413,
    widthUnit: 35,
    heightPx: 531,
    heightUnit: 45,
  },
  "japan-resume": {
    specCode: "japan-resume",
    specCodeInEnglish: "Japan Resume",
    headHeightText: "20 - 24",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 354,
    widthUnit: 30,
    heightPx: 472,
    heightUnit: 40,
  },
  "japan-resume-small-head": {
    specCode: "japan-resume-small-head",
    specCodeInEnglish: "Japan Resume(Portrait)",
    headHeightText: "20 - 24",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 354,
    widthUnit: 30,
    heightPx: 472,
    heightUnit: 40,
  },
  "japan-toeic": {
    specCode: "japan-toeic",
    specCodeInEnglish: "Japan TOEIC",
    headHeightText: "32 - 36",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 354,
    widthUnit: 30,
    heightPx: 472,
    heightUnit: 40,
  },
  "japan-visa": {
    specCode: "japan-visa",
    specCodeInEnglish: "Japan Passport",
    headHeightText: "32 - 36",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 413,
    widthUnit: 35,
    heightPx: 531,
    heightUnit: 45,
  },
  "kenya-passport": {
    specCode: "kenya-passport",
    specCodeInEnglish: "Kenya Passport",
    headHeightText: "32 - 36",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 413,
    widthUnit: 35,
    heightPx: 531,
    heightUnit: 45,
  },
  "kenya-visa": {
    specCode: "kenya-visa",
    specCodeInEnglish: "Kenya VISA",
    headHeightText: "1 - 1 3/8",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "in",
    widthPx: 500,
    widthUnit: 2,
    heightPx: 500,
    heightUnit: 2,
  },
  "kuwait-passport": {
    specCode: "kuwait-passport",
    specCodeInEnglish: "Kuwait Passport",
    headHeightText: "42 - 48",
    eyeToBottomText: "",
    bgColorText: "blue",
    dpi: 300,
    unit: "mm",
    widthPx: 945,
    widthUnit: 40,
    heightPx: 1417,
    heightUnit: 60,
  },
  "kuwait-visa": {
    specCode: "kuwait-visa",
    specCodeInEnglish: "Kuwait VISA",
    headHeightText: "1 - 1 3/8",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "in",
    widthPx: 1200,
    widthUnit: 2,
    heightPx: 1200,
    heightUnit: 2,
  },
  "lebanon-passport": {
    specCode: "lebanon-passport",
    specCodeInEnglish: "Lebanon Passport",
    headHeightText: "32 - 36",
    eyeToBottomText: "29 - 35",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 413,
    widthUnit: 35,
    heightPx: 531,
    heightUnit: 45,
  },
  "lebanon-visa": {
    specCode: "lebanon-visa",
    specCodeInEnglish: "Lebanon VISA",
    headHeightText: "32 - 36",
    eyeToBottomText: "29 - 35",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 413,
    widthUnit: 35,
    heightPx: 531,
    heightUnit: 45,
  },
  linkedin: {
    specCode: "linkedin",
    specCodeInEnglish: "Linkedin",
    headHeightText: "1 - 1 3/8",
    eyeToBottomText: "1 1/8 - 1 3/8",
    bgColorText: "white",
    dpi: 300,
    unit: "in",
    widthPx: 600,
    widthUnit: 2,
    heightPx: 600,
    heightUnit: 2,
  },
  "macao-passport": {
    specCode: "macao-passport",
    specCodeInEnglish: "Macao Passport",
    headHeightText: "32 - 36",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 413,
    widthUnit: 35,
    heightPx: 531,
    heightUnit: 45,
  },
  "macao-visa": {
    specCode: "macao-visa",
    specCodeInEnglish: "Macao VISA",
    headHeightText: "28 - 33",
    eyeToBottomText: "",
    bgColorText: "blue",
    dpi: 300,
    unit: "mm",
    widthPx: 780,
    widthUnit: 33,
    heightPx: 1134,
    heightUnit: 48,
  },
  "malaysia-passport": {
    specCode: "malaysia-passport",
    specCodeInEnglish: "Malaysia Passport",
    headHeightText: "25-30",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 413,
    widthUnit: 35,
    heightPx: 590,
    heightUnit: 50,
  },
  "malaysia-visa": {
    specCode: "malaysia-visa",
    specCodeInEnglish: "Malaysia VISA",
    headHeightText: "35 - 50",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 413,
    widthUnit: 35,
    heightPx: 590,
    heightUnit: 50,
  },
  "mauritius-passport": {
    specCode: "mauritius-passport",
    specCodeInEnglish: "Mauritius Passport",
    headHeightText: "73.3 - 73.3",
    eyeToBottomText: "",
    bgColorText: "off white",
    dpi: 300,
    unit: "mm",
    widthPx: 413,
    widthUnit: 35,
    heightPx: 531,
    heightUnit: 45,
  },
  "mexico-passport": {
    specCode: "mexico-passport",
    specCodeInEnglish: "Mexico Passport",
    headHeightText: "32 - 36",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 413,
    widthUnit: 35,
    heightPx: 531,
    heightUnit: 45,
  },
  "mexico-visa": {
    specCode: "mexico-visa",
    specCodeInEnglish: "Mexico VISA",
    headHeightText: "28 - 31",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 366,
    widthUnit: 31,
    heightPx: 460,
    heightUnit: 39,
  },
  "morocco-evisa": {
    specCode: "morocco-evisa",
    specCodeInEnglish: "Morocco E-Visa",
    headHeightText: "29 - 34",
    eyeToBottomText: "",
    bgColorText: "grey",
    dpi: 300,
    unit: "mm",
    widthPx: 600,
    widthUnit: 35,
    heightPx: 800,
    heightUnit: 45,
  },
  "morocco-passport": {
    specCode: "morocco-passport",
    specCodeInEnglish: "Morocco Passport",
    headHeightText: "32- 36",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 413,
    widthUnit: 35,
    heightPx: 531,
    heightUnit: 45,
  },
  "morocco-visa": {
    specCode: "morocco-visa",
    specCodeInEnglish: "Morocco VISA",
    headHeightText: "32- 36",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 826,
    widthUnit: 35,
    heightPx: 1062,
    heightUnit: 45,
  },
  "myanmar-passport": {
    specCode: "myanmar-passport",
    specCodeInEnglish: "Myanmar Passport",
    headHeightText: "32- 36",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 827,
    widthUnit: 35,
    heightPx: 1063,
    heightUnit: 45,
  },
  "myanmar-visa": {
    specCode: "myanmar-visa",
    specCodeInEnglish: "Myanmar-VISA",
    headHeightText: "33 - 34",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 400,
    widthUnit: 35,
    heightPx: 600,
    heightUnit: 45,
  },
  "neet-passport": {
    specCode: "neet-passport",
    specCodeInEnglish: "NEET Passport",
    headHeightText: "",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "inch",
    widthPx: 750,
    widthUnit: 2.5,
    heightPx: 1050,
    heightUnit: 3.5,
  },
  "neet-postcard": {
    specCode: "neet-postcard",
    specCodeInEnglish: "NEET Postcard",
    headHeightText: "",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "inch",
    widthPx: 1200,
    widthUnit: 4,
    heightPx: 1800,
    heightUnit: 6,
  },
  "nepal-passport": {
    specCode: "nepal-passport",
    specCodeInEnglish: "Nepal Passport",
    headHeightText: "72.2 - 72.2",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 413,
    widthUnit: 35,
    heightPx: 531,
    heightUnit: 45,
  },
  "nepal-visa": {
    specCode: "nepal-visa",
    specCodeInEnglish: "Nepal Visa",
    headHeightText: "72.2 - 72.2",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 413,
    widthUnit: 35,
    heightPx: 531,
    heightUnit: 45,
  },
  "netherlands-driving-license": {
    specCode: "netherlands-driving-license",
    specCodeInEnglish: "Netherlands Driving License",
    headHeightText: "26 - 30",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 400,
    unit: "mm",
    widthPx: 413,
    widthUnit: 35,
    heightPx: 531,
    heightUnit: 45,
  },
  "netherlands-idcard": {
    specCode: "netherlands-idcard",
    specCodeInEnglish: "Netherlands Identity Card",
    headHeightText: "26 - 30",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 400,
    unit: "mm",
    widthPx: 413,
    widthUnit: 35,
    heightPx: 531,
    heightUnit: 45,
  },
  "netherlands-passport": {
    specCode: "netherlands-passport",
    specCodeInEnglish: "Netherlands Passport",
    headHeightText: "26 - 30",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 413,
    widthUnit: 35,
    heightPx: 531,
    heightUnit: 45,
  },
  "netherlands-visa": {
    specCode: "netherlands-visa",
    specCodeInEnglish: "Netherlands VISA",
    headHeightText: "26 - 30",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 400,
    unit: "mm",
    widthPx: 413,
    widthUnit: 35,
    heightPx: 531,
    heightUnit: 45,
  },
  "newyork-gun-license": {
    specCode: "newyork-gun-license",
    specCodeInEnglish: "New York Gun License",
    headHeightText: "",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "in",
    widthPx: 450,
    widthUnit: 1.5,
    heightPx: 450,
    heightUnit: 1.5,
  },
  "newzealand-digital-passport": {
    specCode: "newzealand-digital-passport",
    specCodeInEnglish: "New Zealand Digital Passport",
    headHeightText: "853-960",
    eyeToBottomText: "",
    bgColorText: "gery",
    dpi: 600,
    unit: "px",
    widthPx: 900,
    widthUnit: 900,
    heightPx: 1200,
    heightUnit: 1200,
  },
  "newzealand-online-visa": {
    specCode: "newzealand-online-visa",
    specCodeInEnglish: "New Zealand VISA Online",
    headHeightText: "900-900",
    eyeToBottomText: "",
    bgColorText: "grey",
    dpi: 300,
    unit: "px",
    widthPx: 1650,
    widthUnit: 1650,
    heightPx: 2200,
    heightUnit: 2200,
  },
  "newzealand-paper-visa": {
    specCode: "newzealand-paper-visa",
    specCodeInEnglish: "New Zealand Paper VISA",
    headHeightText: "32-36",
    eyeToBottomText: "",
    bgColorText: "grey",
    dpi: 300,
    unit: "mm",
    widthPx: 413,
    widthUnit: 35,
    heightPx: 531,
    heightUnit: 45,
  },
  "newzealand-passport": {
    specCode: "newzealand-passport",
    specCodeInEnglish: "New Zealand Passport",
    headHeightText: "32 - 36",
    eyeToBottomText: "",
    bgColorText: "grey",
    dpi: 300,
    unit: "mm",
    widthPx: 413,
    widthUnit: 35,
    heightPx: 531,
    heightUnit: 45,
  },
  "newzealand-visa": {
    specCode: "newzealand-visa",
    specCodeInEnglish: "New Zealand VISA",
    headHeightText: "900-900",
    eyeToBottomText: "",
    bgColorText: "grey",
    dpi: 300,
    unit: "px",
    widthPx: 900,
    widthUnit: 900,
    heightPx: 1200,
    heightUnit: 1200,
  },
  "nigeria-passport": {
    specCode: "nigeria-passport",
    specCodeInEnglish: "Nigeria Digital Passport",
    headHeightText: "29 - 34",
    eyeToBottomText: "20 - 30",
    bgColorText: "white",
    dpi: 600,
    unit: "px",
    widthPx: 600,
    widthUnit: 600,
    heightPx: 800,
    heightUnit: 800,
  },
  "nigeria-passport2": {
    specCode: "nigeria-passport2",
    specCodeInEnglish: "Nigeria Digital Passport",
    headHeightText: "29 - 34",
    eyeToBottomText: "20 - 30",
    bgColorText: "white",
    dpi: 600,
    unit: "mm",
    widthPx: 600,
    widthUnit: 35,
    heightPx: 800,
    heightUnit: 45,
  },
  "nigeria-visa": {
    specCode: "nigeria-visa",
    specCodeInEnglish: "Nigeria VISA",
    headHeightText: "32 - 36",
    eyeToBottomText: "20 - 30",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 450,
    widthUnit: 35,
    heightPx: 578,
    heightUnit: 45,
  },
  "norway-passport": {
    specCode: "norway-passport",
    specCodeInEnglish: "Norway Passport",
    headHeightText: "32 - 36",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 413,
    widthUnit: 35,
    heightPx: 531,
    heightUnit: 45,
  },
  "norway-visa": {
    specCode: "norway-visa",
    specCodeInEnglish: "Norway VISA",
    headHeightText: "32 - 36",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 826,
    widthUnit: 35,
    heightPx: 1062,
    heightUnit: 45,
  },
  "oman-passport": {
    specCode: "oman-passport",
    specCodeInEnglish: "Oman Passport",
    headHeightText: "42 - 48",
    eyeToBottomText: "",
    bgColorText: "blue",
    dpi: 300,
    unit: "mm",
    widthPx: 945,
    widthUnit: 40,
    heightPx: 1417,
    heightUnit: 60,
  },
  "oman-visa": {
    specCode: "oman-visa",
    specCodeInEnglish: "Oman VISA",
    headHeightText: "42 - 48",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 945,
    widthUnit: 40,
    heightPx: 1417,
    heightUnit: 60,
  },
  "pakistan-passport": {
    specCode: "pakistan-passport",
    specCodeInEnglish: "Pakistan Passport",
    headHeightText: "29 - 34",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 413,
    widthUnit: 35,
    heightPx: 531,
    heightUnit: 45,
  },
  "pakistan-visa": {
    specCode: "pakistan-visa",
    specCodeInEnglish: "Pakistan VISA",
    headHeightText: "32 - 36",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 413,
    widthUnit: 35,
    heightPx: 531,
    heightUnit: 45,
  },
  "panama-passport": {
    specCode: "panama-passport",
    specCodeInEnglish: "Panama Passport",
    headHeightText: "32 - 36",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 413,
    widthUnit: 35,
    heightPx: 531,
    heightUnit: 45,
  },
  "panama-visa": {
    specCode: "panama-visa",
    specCodeInEnglish: "Panama VISA",
    headHeightText: "1 - 1 3/8",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "in",
    widthPx: 600,
    widthUnit: 2,
    heightPx: 600,
    heightUnit: 2,
  },
  "peru-passport": {
    specCode: "peru-passport",
    specCodeInEnglish: "Peru Passport",
    headHeightText: "1 - 1 3/8",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "in",
    widthPx: 600,
    widthUnit: 2,
    heightPx: 600,
    heightUnit: 2,
  },
  "philippines-passport": {
    specCode: "philippines-passport",
    specCodeInEnglish: "Philippines Passport",
    headHeightText: "32 - 36",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 826,
    widthUnit: 35,
    heightPx: 1062,
    heightUnit: 45,
  },
  "philippines-visa": {
    specCode: "philippines-visa",
    specCodeInEnglish: "Philippines VISA",
    headHeightText: "1 - 1 3/8",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "in",
    widthPx: 1200,
    widthUnit: 2,
    heightPx: 1200,
    heightUnit: 2,
  },
  "poland-passport": {
    specCode: "poland-passport",
    specCodeInEnglish: "Poland Passport",
    headHeightText: "32 - 36",
    eyeToBottomText: "20 - 30",
    bgColorText: "grey",
    dpi: 300,
    unit: "mm",
    widthPx: 413,
    widthUnit: 35,
    heightPx: 531,
    heightUnit: 45,
  },
  "poland-visa": {
    specCode: "poland-visa",
    specCodeInEnglish: "Poland VISA",
    headHeightText: "32 - 36",
    eyeToBottomText: "20 - 30",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 413,
    widthUnit: 35,
    heightPx: 531,
    heightUnit: 45,
  },
  "portugal-passport": {
    specCode: "portugal-passport",
    specCodeInEnglish: "Portugal Passport",
    headHeightText: "32 - 36",
    eyeToBottomText: "20 - 30",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 413,
    widthUnit: 35,
    heightPx: 531,
    heightUnit: 45,
  },
  "portugal-visa": {
    specCode: "portugal-visa",
    specCodeInEnglish: "Portugal VISA",
    headHeightText: "32 - 36",
    eyeToBottomText: "20 - 30",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 413,
    widthUnit: 35,
    heightPx: 531,
    heightUnit: 45,
  },
  "riteaid-passport": {
    specCode: "riteaid-passport",
    specCodeInEnglish: "US Passport",
    headHeightText: "1 - 1 3/8",
    eyeToBottomText: "1 - 1 3/8",
    bgColorText: "white",
    dpi: 300,
    unit: "in",
    widthPx: 600,
    widthUnit: 2,
    heightPx: 600,
    heightUnit: 2,
  },
  "romania-passport": {
    specCode: "romania-passport",
    specCodeInEnglish: "Romania Passport",
    headHeightText: "32 - 36",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 413,
    widthUnit: 35,
    heightPx: 531,
    heightUnit: 45,
  },
  "romania-visa": {
    specCode: "romania-visa",
    specCodeInEnglish: "Romania VISA",
    headHeightText: "28 - 32",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 708,
    widthUnit: 30,
    heightPx: 944,
    heightUnit: 40,
  },
  "russia-passport": {
    specCode: "russia-passport",
    specCodeInEnglish: "Russia Passport",
    headHeightText: "32 - 36",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 413,
    widthUnit: 35,
    heightPx: 531,
    heightUnit: 45,
  },
  "russian-visa": {
    specCode: "russian-visa",
    specCodeInEnglish: "Russian Visa",
    headHeightText: "32 - 36",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 413,
    widthUnit: 35,
    heightPx: 531,
    heightUnit: 45,
  },
  "sat-id": {
    specCode: "sat-id",
    specCodeInEnglish: "SAT ID",
    headHeightText: "64.5 - 64.5",
    eyeToBottomText: "1 1/8 - 1 3/8",
    bgColorText: "white",
    dpi: 300,
    unit: "in",
    widthPx: 600,
    widthUnit: 2,
    heightPx: 600,
    heightUnit: 2,
  },
  "saudiarabia-evisa": {
    specCode: "saudiarabia-evisa",
    specCodeInEnglish: "Saudi Arabia EVISA",
    headHeightText: "1 - 1 3/8",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "px",
    widthPx: 200,
    widthUnit: 200,
    heightPx: 200,
    heightUnit: 200,
  },
  "saudiarabia-passport": {
    specCode: "saudiarabia-passport",
    specCodeInEnglish: "Saudi Arabia Passport",
    headHeightText: "1 - 1 3/8",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "in",
    widthPx: 600,
    widthUnit: 2,
    heightPx: 600,
    heightUnit: 2,
  },
  "saudiarabia-passport-200": {
    specCode: "saudiarabia-passport-200",
    specCodeInEnglish: "Saudi Arabia Passport",
    headHeightText: "14-20",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "px",
    widthPx: 200,
    widthUnit: 200,
    heightPx: 200,
    heightUnit: 200,
  },
  "saudiarabia-visa": {
    specCode: "saudiarabia-visa",
    specCodeInEnglish: "Saudi Arabia  VISA",
    headHeightText: "1 - 1 3/8",
    eyeToBottomText: "1 1/8 - 1 3/8",
    bgColorText: "white",
    dpi: 300,
    unit: "in",
    widthPx: 600,
    widthUnit: 2,
    heightPx: 600,
    heightUnit: 2,
  },
  "schengen-visa": {
    specCode: "schengen-visa",
    specCodeInEnglish: "Schengen VISA",
    headHeightText: "32 - 36",
    eyeToBottomText: "",
    bgColorText: "grey",
    dpi: 300,
    unit: "mm",
    widthPx: 413,
    widthUnit: 35,
    heightPx: 531,
    heightUnit: 45,
  },
  "singapore-passport": {
    specCode: "singapore-passport",
    specCodeInEnglish: "Singapore Passport/IC",
    headHeightText: "25 - 35",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 400,
    widthUnit: 35,
    heightPx: 514,
    heightUnit: 45,
  },
  "singapore-pr": {
    specCode: "singapore-pr",
    specCodeInEnglish: "Singapore Permanent Residence",
    headHeightText: "25 - 35",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 400,
    widthUnit: 35,
    heightPx: 514,
    heightUnit: 45,
  },
  "singapore-visa": {
    specCode: "singapore-visa",
    specCodeInEnglish: "Singapore VISA",
    headHeightText: "25 - 35",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 413,
    widthUnit: 35,
    heightPx: 531,
    heightUnit: 45,
  },
  "southafrica-passport": {
    specCode: "southafrica-passport",
    specCodeInEnglish: "South Africa Passport",
    headHeightText: "29 - 34",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 413,
    widthUnit: 35,
    heightPx: 531,
    heightUnit: 45,
  },
  "southafrica-visa": {
    specCode: "southafrica-visa",
    specCodeInEnglish: "South Africa VISA",
    headHeightText: "29 - 34",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 413,
    widthUnit: 35,
    heightPx: 531,
    heightUnit: 45,
  },
  "southkorea-passport": {
    specCode: "southkorea-passport",
    specCodeInEnglish: "South Korea Passport",
    headHeightText: "25 - 35",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 413,
    widthUnit: 35,
    heightPx: 531,
    heightUnit: 45,
  },
  "southkorea-visa": {
    specCode: "southkorea-visa",
    specCodeInEnglish: "South Korea VISA",
    headHeightText: "25 - 35",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 413,
    widthUnit: 35,
    heightPx: 531,
    heightUnit: 45,
  },
  "spain-dni": {
    specCode: "spain-dni",
    specCodeInEnglish: "Spain DNI",
    headHeightText: "23 - 25",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 307,
    widthUnit: 26,
    heightPx: 378,
    heightUnit: 32,
  },
  "spain-passport": {
    specCode: "spain-passport",
    specCodeInEnglish: "Spain Passport",
    headHeightText: "23 - 25",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 354,
    widthUnit: 30,
    heightPx: 472,
    heightUnit: 40,
  },
  "spain-visa": {
    specCode: "spain-visa",
    specCodeInEnglish: "Spain VISA",
    headHeightText: "32 - 36",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 413,
    widthUnit: 35,
    heightPx: 531,
    heightUnit: 45,
  },
  "student-id-300x300px": {
    specCode: "student-id-300x300px",
    specCodeInEnglish: "Student ID Photo (300x300 Px)",
    headHeightText: "150 - 200",
    eyeToBottomText: "170- 200",
    bgColorText: "white",
    dpi: 300,
    unit: "px",
    widthPx: 300,
    widthUnit: 300,
    heightPx: 300,
    heightUnit: 300,
  },
  "student-id-300x400px": {
    specCode: "student-id-300x400px",
    specCodeInEnglish: "Student ID Photo (300x400 Px)",
    headHeightText: "",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "px",
    widthPx: 300,
    widthUnit: 300,
    heightPx: 400,
    heightUnit: 400,
  },
  "student-id-400x600px": {
    specCode: "student-id-400x600px",
    specCodeInEnglish: "Student ID Photo (400x600 Px)",
    headHeightText: "",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "px",
    widthPx: 400,
    widthUnit: 600,
    heightPx: 400,
    heightUnit: 600,
  },
  "student-id-600x600px": {
    specCode: "student-id-600x600px",
    specCodeInEnglish: "Student ID Photo (600x600 Px)",
    headHeightText: "300-400",
    eyeToBottomText: "350-400",
    bgColorText: "white",
    dpi: 300,
    unit: "px",
    widthPx: 600,
    widthUnit: 600,
    heightPx: 600,
    heightUnit: 600,
  },
  "student-id-900x1200px": {
    specCode: "student-id-900x1200px",
    specCodeInEnglish: "Student ID Photo (900x1200 Px)",
    headHeightText: "",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "px",
    widthPx: 900,
    widthUnit: 900,
    heightPx: 1200,
    heightUnit: 1200,
  },
  "sweden-passport": {
    specCode: "sweden-passport",
    specCodeInEnglish: "Sweden Passport",
    headHeightText: "32 - 36",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 413,
    widthUnit: 35,
    heightPx: 531,
    heightUnit: 45,
  },
  "sweden-visa": {
    specCode: "sweden-visa",
    specCodeInEnglish: "Sweden VISA",
    headHeightText: "32 - 36",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 413,
    widthUnit: 35,
    heightPx: 531,
    heightUnit: 45,
  },
  "sweden-work": {
    specCode: "sweden-work",
    specCodeInEnglish: "Sweden Work",
    headHeightText: "29 - 34",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 1200,
    unit: "mm",
    widthPx: 1652,
    widthUnit: 35,
    heightPx: 2124,
    heightUnit: 45,
  },
  "sweden-work-600-dpi": {
    specCode: "sweden-work-600-dpi",
    specCodeInEnglish: "Sweden Work",
    headHeightText: "29 - 34",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 600,
    unit: "mm",
    widthPx: 826,
    widthUnit: 35,
    heightPx: 1062,
    heightUnit: 45,
  },
  "switzerland-foreign-residence-permit": {
    specCode: "switzerland-foreign-residence-permit",
    specCodeInEnglish: "Switzerland Foreign Residence Permit",
    headHeightText: "64.5 - 75.5",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 413,
    widthUnit: 35,
    heightPx: 531,
    heightUnit: 45,
  },
  "switzerland-passport": {
    specCode: "switzerland-passport",
    specCodeInEnglish: "Switzerland Passport",
    headHeightText: "32 - 36",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 413,
    widthUnit: 35,
    heightPx: 531,
    heightUnit: 45,
  },
  "switzerland-visa": {
    specCode: "switzerland-visa",
    specCodeInEnglish: "Switzerland VISA",
    headHeightText: "32 - 36",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 413,
    widthUnit: 35,
    heightPx: 531,
    heightUnit: 45,
  },
  "syria-passport": {
    specCode: "syria-passport",
    specCodeInEnglish: "Syria Passport",
    headHeightText: "1 - 1 3/8",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "in",
    widthPx: 1200,
    widthUnit: 2,
    heightPx: 1200,
    heightUnit: 2,
  },
  "syria-visa": {
    specCode: "syria-visa",
    specCodeInEnglish: "Syria VISA",
    headHeightText: "1 - 1 3/8",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "in",
    widthPx: 1200,
    widthUnit: 2,
    heightPx: 1200,
    heightUnit: 2,
  },
  "taiwan-halfbody": {
    specCode: "taiwan-halfbody",
    specCodeInEnglish: "Taiwan Two Inch Half Body",
    headHeightText: "23 - 26",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 496,
    widthUnit: 42,
    heightPx: 555,
    heightUnit: 47,
  },
  "taiwan-idphoto": {
    specCode: "taiwan-idphoto",
    specCodeInEnglish: "Taiwan ID",
    headHeightText: "",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 413,
    widthUnit: 35,
    heightPx: 531,
    heightUnit: 45,
  },
  "taiwan-oneinch": {
    specCode: "taiwan-oneinch",
    specCodeInEnglish: "Taiwan One Inch",
    headHeightText: "",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 331,
    widthUnit: 28,
    heightPx: 413,
    heightUnit: 35,
  },
  "taiwan-oneinchhalfbody": {
    specCode: "taiwan-oneinchhalfbody",
    specCodeInEnglish: "Taiwan One Inch Half Body",
    headHeightText: "17 - 19",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 331,
    widthUnit: 28,
    heightPx: 413,
    heightUnit: 35,
  },
  "taiwan-passport": {
    specCode: "taiwan-passport",
    specCodeInEnglish: "Taiwan Passport",
    headHeightText: "32 - 36",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 413,
    widthUnit: 35,
    heightPx: 531,
    heightUnit: 45,
  },
  "taiwan-twoinch": {
    specCode: "taiwan-twoinch",
    specCodeInEnglish: "Taiwan Two Inch",
    headHeightText: "",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 413,
    widthUnit: 35,
    heightPx: 531,
    heightUnit: 45,
  },
  "taiwan-visa": {
    specCode: "taiwan-visa",
    specCodeInEnglish: "Taiwan Entry Permit",
    headHeightText: "32 - 36",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 413,
    widthUnit: 35,
    heightPx: 531,
    heightUnit: 45,
  },
  "tanzania-passport": {
    specCode: "tanzania-passport",
    specCodeInEnglish: "Tanzania Passport",
    headHeightText: "32 - 36",
    eyeToBottomText: "",
    bgColorText: "blue",
    dpi: 300,
    unit: "mm",
    widthPx: 944,
    widthUnit: 40,
    heightPx: 1062,
    heightUnit: 45,
  },
  "tanzania-visa": {
    specCode: "tanzania-visa",
    specCodeInEnglish: "Tanzania VISA",
    headHeightText: "1 - 1 3/8",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "in",
    widthPx: 600,
    widthUnit: 2,
    heightPx: 600,
    heightUnit: 2,
  },
  "texas-id": {
    specCode: "texas-id",
    specCodeInEnglish: "Texas ID",
    headHeightText: "1 - 1 3/8",
    eyeToBottomText: "1 1/8 - 1 3/8",
    bgColorText: "white",
    dpi: 300,
    unit: "in",
    widthPx: 600,
    widthUnit: 2,
    heightPx: 600,
    heightUnit: 2,
  },
  "thailand-passport": {
    specCode: "thailand-passport",
    specCodeInEnglish: "Thailand Passport",
    headHeightText: "32 - 36",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 413,
    widthUnit: 35,
    heightPx: 531,
    heightUnit: 45,
  },
  "thailand-visa": {
    specCode: "thailand-visa",
    specCodeInEnglish: "Thailand VISA(40*60)",
    headHeightText: "42 - 48",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 427,
    widthUnit: 40,
    heightPx: 709,
    heightUnit: 60,
  },
  "theunitedarabemirates-passport": {
    specCode: "theunitedarabemirates-passport",
    specCodeInEnglish: "The United Arab Emirates Passport",
    headHeightText: "42 - 48",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 945,
    widthUnit: 40,
    heightPx: 1417,
    heightUnit: 60,
  },
  "theunitedarabemirates-visa": {
    specCode: "theunitedarabemirates-visa",
    specCodeInEnglish: "The United Arab Emirates VISA",
    headHeightText: "32 - 36",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 413,
    widthUnit: 35,
    heightPx: 531,
    heightUnit: 45,
  },
  "trinidadandtobago-passport": {
    specCode: "trinidadandtobago-passport",
    specCodeInEnglish: "Trinidad and Tobago Passport",
    headHeightText: "29 - 32",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 732,
    widthUnit: 31,
    heightPx: 968,
    heightUnit: 41,
  },
  "turkey-passport": {
    specCode: "turkey-passport",
    specCodeInEnglish: "Turkey Passport",
    headHeightText: "42 - 48",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 590,
    widthUnit: 50,
    heightPx: 708,
    heightUnit: 60,
  },
  "turkey-visa": {
    specCode: "turkey-visa",
    specCodeInEnglish: "Turkey VISA",
    headHeightText: "42 - 48",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 590,
    widthUnit: 50,
    heightPx: 708,
    heightUnit: 60,
  },
  "turkish-residence-card": {
    specCode: "turkish-residence-card",
    specCodeInEnglish: "Turkish Residence Card",
    headHeightText: "56.7 - 56.7",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 590,
    widthUnit: 50,
    heightPx: 708,
    heightUnit: 60,
  },
  "uae-driving-license": {
    specCode: "uae-driving-license",
    specCodeInEnglish: "UAE Driving License",
    headHeightText: "37.8 - 37.8",
    eyeToBottomText: "20 - 30",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 472,
    widthUnit: 40,
    heightPx: 708,
    heightUnit: 60,
  },
  "uae-evisa": {
    specCode: "uae-evisa",
    specCodeInEnglish: "UAE eVISA",
    headHeightText: "265.68 - 265.68",
    eyeToBottomText: "20 - 30",
    bgColorText: "white",
    dpi: 300,
    unit: "px",
    widthPx: 300,
    widthUnit: 300,
    heightPx: 369,
    heightUnit: 369,
  },
  "uae-family-book": {
    specCode: "uae-family-book",
    specCodeInEnglish: "UAE Family Book",
    headHeightText: "33.75 - 33.75",
    eyeToBottomText: "20 - 30",
    bgColorText: "white",
    dpi: 600,
    unit: "mm",
    widthPx: 413,
    widthUnit: 35,
    heightPx: 531,
    heightUnit: 45,
  },
  "uae-id-card": {
    specCode: "uae-id-card",
    specCodeInEnglish: "UAE ID Card",
    headHeightText: "27.2 - 30.8",
    eyeToBottomText: "20 - 30",
    bgColorText: "white",
    dpi: 600,
    unit: "mm",
    widthPx: 413,
    widthUnit: 35,
    heightPx: 472,
    heightUnit: 40,
  },
  "uae-passport": {
    specCode: "uae-passport",
    specCodeInEnglish: "UAE Passport",
    headHeightText: "37.8 - 37.8",
    eyeToBottomText: "20 - 30",
    bgColorText: "grey",
    dpi: 300,
    unit: "mm",
    widthPx: 472,
    widthUnit: 40,
    heightPx: 708,
    heightUnit: 60,
  },
  "uae-register-arrival": {
    specCode: "uae-register-arrival",
    specCodeInEnglish: "UAE Register Arrival",
    headHeightText: "1.3 - 1.3",
    eyeToBottomText: "20 - 30",
    bgColorText: "white",
    dpi: 300,
    unit: "inch",
    widthPx: 600,
    widthUnit: 2,
    heightPx: 600,
    heightUnit: 2,
  },
  "uae-residence": {
    specCode: "uae-residence",
    specCodeInEnglish: "UAE Residence",
    headHeightText: "24.8 - 26",
    eyeToBottomText: "20 - 30",
    bgColorText: "white",
    dpi: 594,
    unit: "mm",
    widthPx: 413,
    widthUnit: 35,
    heightPx: 472,
    heightUnit: 40,
  },
  "uae-visa": {
    specCode: "uae-visa",
    specCodeInEnglish: "UAE VISA",
    headHeightText: "38.5 - 41.25",
    eyeToBottomText: "20 - 30",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 507,
    widthUnit: 43,
    heightPx: 649,
    heightUnit: 55,
  },
  "uganda-visa": {
    specCode: "uganda-visa",
    specCodeInEnglish: "Uganda Visa",
    headHeightText: "1 - 1 3/8",
    eyeToBottomText: "1 1/8 - 1 3/8",
    bgColorText: "white",
    dpi: 300,
    unit: "in",
    widthPx: 600,
    widthUnit: 2,
    heightPx: 600,
    heightUnit: 2,
  },
  "uk-baby-passport": {
    specCode: "uk-baby-passport",
    specCodeInEnglish: "UK Provisional Driving License",
    headHeightText: "65 - 75",
    eyeToBottomText: "",
    bgColorText: "off white",
    dpi: 300,
    unit: "mm",
    widthPx: 413,
    widthUnit: 35,
    heightPx: 531,
    heightUnit: 45,
  },
  "uk-bno-digital": {
    specCode: "uk-bno-digital",
    specCodeInEnglish: "UK British National Overseas Passport",
    headHeightText: "29 - 34",
    eyeToBottomText: "",
    bgColorText: "",
    dpi: 600,
    unit: "mm",
    widthPx: 600,
    widthUnit: 35,
    heightPx: 750,
    heightUnit: 45,
  },
  "uk-bus-pass": {
    specCode: "uk-bus-pass",
    specCodeInEnglish: "UK Bus Pass",
    headHeightText: "65 - 75",
    eyeToBottomText: "",
    bgColorText: "off white",
    dpi: 300,
    unit: "mm",
    widthPx: 413,
    widthUnit: 35,
    heightPx: 531,
    heightUnit: 45,
  },
  "uk-citizencard": {
    specCode: "uk-citizencard",
    specCodeInEnglish: "UK CitizenCard",
    headHeightText: "438 - 528",
    eyeToBottomText: "",
    bgColorText: "grey",
    dpi: 300,
    unit: "px",
    widthPx: 480,
    widthUnit: 480,
    heightPx: 680,
    heightUnit: 680,
  },
  "uk-digital-passport": {
    specCode: "uk-digital-passport",
    specCodeInEnglish: "UK Digital Passport",
    headHeightText: "37%",
    eyeToBottomText: "",
    bgColorText: "gery",
    dpi: 600,
    unit: "px",
    widthPx: 600,
    widthUnit: 600,
    heightPx: 750,
    heightUnit: 750,
  },
  "uk-driverlicense": {
    specCode: "uk-driverlicense",
    specCodeInEnglish: "UK Driver License",
    headHeightText: "29 - 34",
    eyeToBottomText: "",
    bgColorText: "grey",
    dpi: 300,
    unit: "mm",
    widthPx: 413,
    widthUnit: 35,
    heightPx: 531,
    heightUnit: 45,
  },
  "uk-passport": {
    specCode: "uk-passport",
    specCodeInEnglish: "UK Passport",
    headHeightText: "29 - 34",
    eyeToBottomText: "",
    bgColorText: "grey",
    dpi: 300,
    unit: "mm",
    widthPx: 413,
    widthUnit: 35,
    heightPx: 531,
    heightUnit: 45,
  },
  "uk-provisional-driving-license": {
    specCode: "uk-provisional-driving-license",
    specCodeInEnglish: "UK Provisional Driving License",
    headHeightText: "65 - 75",
    eyeToBottomText: "",
    bgColorText: "off white",
    dpi: 300,
    unit: "mm",
    widthPx: 413,
    widthUnit: 35,
    heightPx: 531,
    heightUnit: 45,
  },
  "uk-railcard": {
    specCode: "uk-railcard",
    specCodeInEnglish: "UK Railcard",
    headHeightText: "70 - 70",
    eyeToBottomText: "",
    bgColorText: "off white",
    dpi: 300,
    unit: "mm",
    widthPx: 413,
    widthUnit: 35,
    heightPx: 531,
    heightUnit: 45,
  },
  "uk-student-id-card": {
    specCode: "uk-student-id-card",
    specCodeInEnglish: "UK Student ID Card",
    headHeightText: "76.7 - 76.7",
    eyeToBottomText: "",
    bgColorText: "off white",
    dpi: 300,
    unit: "mm",
    widthPx: 413,
    widthUnit: 35,
    heightPx: 531,
    heightUnit: 45,
  },
  "uk-visa": {
    specCode: "uk-visa",
    specCodeInEnglish: "UK VISA",
    headHeightText: "29 - 34",
    eyeToBottomText: "",
    bgColorText: "grey",
    dpi: 300,
    unit: "mm",
    widthPx: 413,
    widthUnit: 35,
    heightPx: 531,
    heightUnit: 45,
  },
  "ukraine-passport": {
    specCode: "ukraine-passport",
    specCodeInEnglish: "Ukraine Passport",
    headHeightText: "32 - 36",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 413,
    widthUnit: 35,
    heightPx: 531,
    heightUnit: 45,
  },
  "ukraine-visa": {
    specCode: "ukraine-visa",
    specCodeInEnglish: "Ukraine VISA",
    headHeightText: "28 - 32",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 450,
    widthUnit: 30,
    heightPx: 600,
    heightUnit: 40,
  },
  "ups-passport": {
    specCode: "ups-passport",
    specCodeInEnglish: "UPS Passport",
    headHeightText: "1 - 1 3/8",
    eyeToBottomText: "1 - 1 3/8",
    bgColorText: "white",
    dpi: 300,
    unit: "in",
    widthPx: 600,
    widthUnit: 2,
    heightPx: 600,
    heightUnit: 2,
  },
  "us-dvlottery": {
    specCode: "us-dvlottery",
    specCodeInEnglish: "US DV Lottery",
    headHeightText: "1 - 1 3/8",
    eyeToBottomText: "1 1/8 - 1 3/8",
    bgColorText: "white",
    dpi: 300,
    unit: "in",
    widthPx: 600,
    widthUnit: 2,
    heightPx: 600,
    heightUnit: 2,
  },
  "us-ead": {
    specCode: "us-ead",
    specCodeInEnglish: "US Passport",
    headHeightText: "1 - 1 3/8",
    eyeToBottomText: "1 - 1 3/8",
    bgColorText: "white",
    dpi: 300,
    unit: "in",
    widthPx: 600,
    widthUnit: 2,
    heightPx: 600,
    heightUnit: 2,
  },
  "us-greencard": {
    specCode: "us-greencard",
    specCodeInEnglish: "US Green Card",
    headHeightText: "1 - 1 3/8",
    eyeToBottomText: "1 1/8 - 1 3/8",
    bgColorText: "white",
    dpi: 300,
    unit: "in",
    widthPx: 600,
    widthUnit: 2,
    heightPx: 600,
    heightUnit: 2,
  },
  "us-nursing-license": {
    specCode: "us-nursing-license",
    specCodeInEnglish: "US Passport",
    headHeightText: "1 - 1 3/8",
    eyeToBottomText: "1 - 1 3/8",
    bgColorText: "white",
    dpi: 300,
    unit: "in",
    widthPx: 600,
    widthUnit: 2,
    heightPx: 600,
    heightUnit: 2,
  },
  "us-opt": {
    specCode: "us-opt",
    specCodeInEnglish: "US F1 OPT",
    headHeightText: "1 - 1 3/8",
    eyeToBottomText: "1 - 1 3/8",
    bgColorText: "white",
    dpi: 300,
    unit: "in",
    widthPx: 600,
    widthUnit: 2,
    heightPx: 600,
    heightUnit: 2,
  },
  "us-passport": {
    specCode: "us-passport",
    specCodeInEnglish: "US Passport ",
    headHeightText: "1 - 1 3/8",
    eyeToBottomText: "1 1/8 - 1 3/8",
    bgColorText: "white",
    dpi: 300,
    unit: "in",
    widthPx: 600,
    widthUnit: 2,
    heightPx: 600,
    heightUnit: 2,
  },
  "us-passport-card": {
    specCode: "us-passport-card",
    specCodeInEnglish: "US Passport Card",
    headHeightText: "1 - 1 3/8",
    eyeToBottomText: "1 1/8 - 1 3/8",
    bgColorText: "white",
    dpi: 300,
    unit: "in",
    widthPx: 600,
    widthUnit: 2,
    heightPx: 600,
    heightUnit: 2,
  },
  "us-visa": {
    specCode: "us-visa",
    specCodeInEnglish: "US VISA",
    headHeightText: "1 - 1 3/8",
    eyeToBottomText: "1 1/8 - 1 3/8",
    bgColorText: "white",
    dpi: 300,
    unit: "in",
    widthPx: 600,
    widthUnit: 2,
    heightPx: 600,
    heightUnit: 2,
  },
  "uscis-passport": {
    specCode: "uscis-passport",
    specCodeInEnglish: "US Passport",
    headHeightText: "1 - 1 3/8",
    eyeToBottomText: "1 - 1 3/8",
    bgColorText: "white",
    dpi: 300,
    unit: "in",
    widthPx: 600,
    widthUnit: 2,
    heightPx: 600,
    heightUnit: 2,
  },
  "uzbekistan-passport": {
    specCode: "uzbekistan-passport",
    specCodeInEnglish: "Uzbekistan Passport",
    headHeightText: "32 - 36",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 413,
    widthUnit: 35,
    heightPx: 531,
    heightUnit: 45,
  },
  "uzbekistan-visa": {
    specCode: "uzbekistan-visa",
    specCodeInEnglish: "Uzbekistan VISA",
    headHeightText: "32 - 36",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 413,
    widthUnit: 35,
    heightPx: 531,
    heightUnit: 45,
  },
  "venezuela-passport": {
    specCode: "venezuela-passport",
    specCodeInEnglish: "Venezuela Passport",
    headHeightText: "1 - 1 3/8",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "in",
    widthPx: 1200,
    widthUnit: 2,
    heightPx: 1200,
    heightUnit: 2,
  },
  "venezuela-visa": {
    specCode: "venezuela-visa",
    specCodeInEnglish: "Venezuela VISA",
    headHeightText: "1 - 1 3/8",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "in",
    widthPx: 1200,
    widthUnit: 2,
    heightPx: 1200,
    heightUnit: 2,
  },
  "vietnam-evisa": {
    specCode: "vietnam-evisa",
    specCodeInEnglish: "Vietnam E visa",
    headHeightText: "1- 1 3/8",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 600,
    unit: "mm",
    widthPx: 472,
    widthUnit: 40,
    heightPx: 708,
    heightUnit: 60,
  },
  "vietnam-passport": {
    specCode: "vietnam-passport",
    specCodeInEnglish: "Vietnam Passport",
    headHeightText: "42 - 48",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 472,
    widthUnit: 40,
    heightPx: 708,
    heightUnit: 60,
  },
  "vietnam-visa": {
    specCode: "vietnam-visa",
    specCodeInEnglish: "Vietnam VISA",
    headHeightText: "1 - 1 3/8",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 472,
    widthUnit: 40,
    heightPx: 708,
    heightUnit: 60,
  },
  "walgreen-passport": {
    specCode: "walgreen-passport",
    specCodeInEnglish: "Walgreeen Passport",
    headHeightText: "1 - 1 3/8",
    eyeToBottomText: "1 - 1 3/8",
    bgColorText: "white",
    dpi: 300,
    unit: "in",
    widthPx: 600,
    widthUnit: 2,
    heightPx: 600,
    heightUnit: 2,
  },
  "zimbabwe-passport": {
    specCode: "zimbabwe-passport",
    specCodeInEnglish: "Zimbabwe Passport",
    headHeightText: "32 - 36",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 413,
    widthUnit: 35,
    heightPx: 531,
    heightUnit: 45,
  },
  "zimbabwe-visa": {
    specCode: "zimbabwe-visa",
    specCodeInEnglish: "Zimbabwe VISA",
    headHeightText: "32 - 36",
    eyeToBottomText: "",
    bgColorText: "white",
    dpi: 300,
    unit: "mm",
    widthPx: 413,
    widthUnit: 35,
    heightPx: 531,
    heightUnit: 45,
  },
};
